### PR TITLE
pull request from jiahui

### PR DESCRIPTION
**Pull request by teddyljh**
hope to merge the new changes in the original repo and mine

### CODE REVIEW

**Comment by thomasWeise** [comment]
Dear Jiahui.

Thanks for this great contribution. The code looks quite good.
Could you perform some minor updates before I merge it in?
1. Some of the methods (constructors, main method) and the classes themselves are not yet annotated with JavaDoc comments (some have // comments, but not /*\* */). If you would add these comments, this will make it much easier for future users of your code to understand how it works.
2. I am not really sure about the line `( temp < criticalTemp && metroProbability <=   r.nextDouble() && constProbability >  r.nextDouble()))`: I think that the check `metroProbability <=   r.nextDouble()` may not be necessary. I may be wrong, but think you want to check that the previous criterion is false, but this may not be necessary (as we would not get to that line if it had been true). Moreover `r.nextDouble()` will return a different value every time. (But I may misunderstand your code).
3. Please also make sure to exist your main loops (e.g., `while (temp > 1)`) when `f.shouldTerminate()` becomes `false`. The reason is that otherwise, the loops may run for a very long time, if the cooling schedule or initial temperature are not set properly. Also, they will continue to run even after the global optimum was found. If you do  `while ((temp > 1) && (!(f.shouldTerminate)))` instead, they will terminate when the assigned runtime is exhausted or the optimum was found.

If you could apply these minor changes, the algorithm would be perfect and I can pull it into our repository.

**Comment by teddyljh** [comment]
Dear Thomas,
          Thank you for the comment!

```
       I'm editing the code regarding the issues 1, 3 .

      Regarding the metroProbability < r.nextDouble() part, I think I
```

should use the same randomly generated number to check both
metroProbability and constProbability:

```
       double randomCheck = r.nextDouble();

   if (( metroProbability > randomCheck) ||
  ( temp < criticalTemp && metroProbability <=   randomCheck &&
```

constProbability >  randomCheck))

```
       But I'm not sure if I should remove metroProbability <=
```

randomCheck or not. Because what I understand is that even under the
critical temperature, we use constant probability only if the update is
rejected by metropolis probability. Do I get this wrong?

2015-06-04 10:27 GMT+08:00 Thomas Weise notifications@github.com:

**Comment by thomasWeise** [comment]
Dear Jiahui.

First of all, sorry for my late answer.

> Because what I understand is that even under the
> critical temperature, we use constant probability only if the update is
> rejected by metropolis probability. Do I get this wrong?

Hm, but if the update is accepted by the Metropolis criterion, then it already is accepted. We cannot accept it twice. Or, if we would, it would change nothing. So from this perspective, unless I misunderstand something, it seems to me that it doesn't matter.

Additionally, from some first glances over the the code - again, unless I misunderstand something - I think that unless metroProbability is `NaN`, the check `(metroProbability <= randomCheck)` seems to be redundant. It seems that we would only check `(temp < criticalTemp) && (constProbability >  randomCheck)` if `(metroProbability > randomCheck)` is _not_ true, i.e., if `(metroProbability <= randomCheck)` holds.

The code

``` java
if((metroProbability > randomCheck) ||
   ( (temp < criticalTemp) && (metroProbability <= randomCheck)
                           && (constProbability >  randomCheck))) {
   // do my thing
}
```

can be re-written as

``` java
if(metroProbability > randomCheck) {
  // do my thing
} else {
  if ( (temp < criticalTemp) && (metroProbability <= randomCheck)
                             && (constProbability >  randomCheck)) {
   // do my thing
  }
}
```

which can be re-written as

``` java
if(metroProbability > randomCheck) {
  // do my thing
} else {
  if (metroProbability <= randomCheck) {
    if ( (temp < criticalTemp) && (constProbability >  randomCheck))) {
     // do my thing
    }
  }
}
```

This then again can be re-written as

``` java
if(metroProbability > randomCheck) {
  // do my thing
} 

if(!(metroProbability > randomCheck)) {
  if (metroProbability <= randomCheck) {
    if ( (temp < criticalTemp) && (constProbability >  randomCheck))) {
     // do my thing
    }
  }
}
```

Anyway, this is a _very small_ issue. Whether or not we have one more floating point comparison in the code plays no role performance wise. I just wrote this to double-check if I have a misunderstanding.

Cheers,
  Thomas.

**Comment by teddyljh** [comment]
Dear Thomas,
        Thank you very much. I got the point.

2015-06-05 16:00 GMT+08:00 Thomas Weise notifications@github.com:

**Pull request merged**
